# Generated by Django 5.2.1 on 2025-06-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('member_id', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('others', 'others')], max_length=10)),
                ('joining_date', models.DateField()),
                ('member_level', models.CharField(max_length=100)),
                ('mobil_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('public_number', models.CharField()),
                ('member_picture', models.ImageField(blank=True, upload_to='vdvore/')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('numbers_of_movies', models.CharField(choices=[('Nothing', 'Nothing'), ('< 10', '< 10'), ('10 to 30', '10 to 30'), ('> 30', '> 30')], max_length=50)),
            ],
        ),
    ]
