# Generated by Django 5.2.1 on 2025-06-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdvore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_level',
            new_name='category_member',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='mobil_number',
            new_name='mobile_number',
        ),
        migrations.AlterField(
            model_name='member',
            name='numbers_of_movies',
            field=models.CharField(choices=[('Nothing', 'Nothing'), ('< 10', '< 10'), ('10 to 30', '10 to 30'), ('30 >', '30 >')], max_length=50),
        ),
    ]
